version: '3.1'

networks:
  http_network:
    external: true

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - http_network


  adminer:
    image: adminer
    restart: always
    networks:
      - http_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${FQDN}`) && PathPrefix(`/adminer`)"
      - "traefik.http.routers.adminer.entrypoints=websecure"

  django:
    build: ./dj_base
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fixtures:/fixtures
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - http_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`${FQDN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.django.entrypoints=websecure"
